collections:
 posts:
   output: true
   permalink: /posts/:slug

_select_data:
  background-colors:
    bg-sky-200: Light Background
    bg-sky-500: Dark Background
    bg-white: White Background
  col-sizes:
    md:grid-cols-1: 1 Column
    md:grid-cols-2: 2 Columns
    md:grid-cols-3: 3 Columns
    md:grid-cols-4: 4 Columns
  image-positions:
    left: Left
    right: Right      

page_blocks: []

_array_structures:
  page_blocks:
    - label: Title section
      icon: article
      value: 
        _id: title_section
        title: Title section
        heading: What to do in Vancouver
        author: Tara Hunka
        category: travel
        date: 2022-11-21
    - label: Banner with text
      icon: article
      value: 
        _id: banner_text
        title: Banner with text
        text: Write your text here
        featured-image: https://images.unsplash.com/photo-1511489731872-324afc650052?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=988&q=80
        overlay: true
    - label: Content Block / Image Left
      icon: article
      value:
        _id: text_image_left
        title: Content Block / Image Left
        background-color: bg-white
        image-position: 
        heading: Beautiful Ontario
        col-1-html: Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus
          deserunt corrupti autem blanditiis doloremque, aut illo nemo perferendis
          eligendi quas consequatur perspiciatis laudantium sint voluptatum eum esse
          quisquam repellendus molestiae. Lorem ipsum dolor sit amet consectetur
          adipisicing elit. Temporibus deserunt corrupti autem blanditiis
          doloremque, aut illo nemo perferendis eligendi quas consequatur
          perspiciatis laudantium sint voluptatum eum esse quisquam repellendus
          molestiae. Lorem ipsum dolor sit amet consectetur adipisicing elit.
          Temporibus deserunt corrupti autem blanditiis doloremque, aut illo nemo
          perferendis eligendi quas consequatur perspiciatis laudantium sint
          voluptatum eum esse quisquam repellendus molestiae.
        image-url: https://images.unsplash.com/photo-1617803672592-177dbdb3abfa?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80
    - label: Content Block / Image Right
      icon: article
      value:
        id: text_image_right
        title: Content Block / Image Right
        heading: Beautiful Ontario
        col-1-html: Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus
          deserunt corrupti autem blanditiis doloremque, aut illo nemo perferendis
          eligendi quas consequatur perspiciatis laudantium sint voluptatum eum esse
          quisquam repellendus molestiae. Lorem ipsum dolor sit amet consectetur
          adipisicing elit. Temporibus deserunt corrupti autem blanditiis
          doloremque, aut illo nemo perferendis eligendi quas consequatur
          perspiciatis laudantium sint voluptatum eum esse quisquam repellendus
          molestiae. Lorem ipsum dolor sit amet consectetur adipisicing elit.
          Temporibus deserunt corrupti autem blanditiis doloremque, aut illo nemo
          perferendis eligendi quas consequatur perspiciatis laudantium sint
          voluptatum eum esse quisquam repellendus molestiae.
        image-url: https://images.unsplash.com/photo-1617803672592-177dbdb3abfa?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80
    - label: Video embed
      icon: article
      value:
        _id: embed_video
        title: Video
        video-url: https://www.youtube.com/embed/WteZwxsvICc
    - label: Gallery
      icon: article
      value:    
        _id: gallery
        title: Gallery
        gallery:
          - image: https://images.unsplash.com/photo-1508693926297-1d61ee3df82a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80
          - image: https://images.unsplash.com/photo-1503614472-8c93d56e92ce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2011&q=80
          - image: https://images.unsplash.com/photo-1490623970972-ae8bb3da443e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGNhbmFkYXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=900&q=60
          - image: https://images.unsplash.com/photo-1511489731872-324afc650052?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=988&q=80
          - image: https://images.unsplash.com/photo-1617803672592-177dbdb3abfa?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80
          - image: https://images.unsplash.com/photo-1586576782138-19304c43d0e1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80
    - label: Text
      icon: article
      value:    
        _id: text
        title: Text
        col-size: md:grid-cols-1
        heading_1: What a great text
        copy_1_html: Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus
          deserunt corrupti autem blanditiis doloremque, aut illo nemo perferendis
          eligendi quas consequatur perspiciatis laudantium sint voluptatum eum esse
          quisquam repellendus molestiae. Lorem ipsum dolor sit amet consectetur
          adipisicing elit.
        heading_2: What a great text
        copy_2_html: Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus
          deserunt corrupti autem blanditiis doloremque, aut illo nemo perferendis
          eligendi quas consequatur perspiciatis laudantium sint voluptatum eum esse
          quisquam repellendus molestiae. Lorem ipsum dolor sit amet consectetur
          adipisicing elit.
        heading_3: What a great text
        copy_3_html: Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus
          deserunt corrupti autem blanditiis doloremque, aut illo nemo perferendis
          eligendi quas consequatur perspiciatis laudantium sint voluptatum eum esse
          quisquam repellendus molestiae. Lorem ipsum dolor sit amet consectetur
          adipisicing elit.
        heading_4: What a great text
        copy_4_html: Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus
          deserunt corrupti autem blanditiis doloremque, aut illo nemo perferendis
          eligendi quas consequatur perspiciatis laudantium sint voluptatum eum esse
          quisquam repellendus molestiae. Lorem ipsum dolor sit amet consectetur
          adipisicing elit.     